name: Build previews

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [ '16' ]

    steps:
      - uses: actions/checkout

      - name: Setup Node
        uses: actions/setup-node
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Yarn dependencies
        run: yarn

      - name: Run tests
        run: yarn build

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
