name: Build previews

on:
  push:
    branches: [ main, gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node_version: [ '16' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'

      - name: Install Yarn dependencies
        run: yarn

      - name: Run tests
        run: yarn build

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.WEB_CICD_PAT }}
          publish_branch: gh-pages
          publish_dir: ./docs
